name: gober
services:

  mysql:
    image: mysql:latest
    container_name: gober-mysql
    hostname: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:latest
    container_name: gober-redis
    hostname: redis
    restart: unless-stopped
    ports:
      - '6379:6379'